# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/vocabBuilder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wordOutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.wordOutput.setGeometry(QtCore.QRect(150, 120, 401, 61))
        self.wordOutput.setObjectName("wordOutput")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.wordOutput.setFont(font)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 30, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.generatePb = QtWidgets.QPushButton(self.centralwidget)
        self.generatePb.setGeometry(QtCore.QRect(220, 420, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.generatePb.setFont(font)
        self.generatePb.setObjectName("generatePb")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.meaningOutput = QtWidgets.QTextBrowser(self.centralwidget)
        self.meaningOutput.setGeometry(QtCore.QRect(150, 190, 401, 192))
        self.meaningOutput.setObjectName("meaningOutput")
        self.meaningOutput.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "A Word Every Day"))
        self.label.setText(_translate("MainWindow", "Word of the Day"))
        self.generatePb.setText(_translate("MainWindow", "Generate!"))
